FROM python:3

WORKDIR /usr/src

COPY nbdime/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY nbdime/original.ipynb .

CMD ["nbdiff-web", "-p=81", "--ip=0.0.0.0", "--base-url=/d/", "original.ipynb", "original.ipynb"]